# Generated by Django 5.1 on 2024-08-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='department',
            field=models.IntegerField(choices=[(0, 'Human Resources'), (1, 'Finance'), (2, 'IT'), (3, 'Marketing')], default=0),
        ),
    ]
