# Generated by Django 5.0.8 on 2024-11-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slaentry',
            old_name='service_description',
            new_name='key_performance_area',
        ),
    ]
