# Generated by Django 5.0.8 on 2024-11-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_service_description_slaentry_key_performance_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaentry',
            name='service_provider_responsibility',
            field=models.TextField(blank=True, default=''),
        ),
    ]
