# Generated by Django 5.1 on 2024-08-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_authuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField(choices=[(0, 'Human Resources'), (1, 'Finance'), (2, 'IT'), (3, 'Marketing')])),
                ('service_description', models.TextField(max_length=2000)),
                ('customer_responsibility', models.TextField(max_length=1500)),
                ('service_level', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
