# Generated by Django 5.1 on 2024-08-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slaentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaentry',
            name='service_level',
            field=models.TextField(max_length=1500),
        ),
    ]
