# Generated by Django 5.0.8 on 2025-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slaentry_service_provider_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slarating',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
