# Generated by Django 5.1 on 2024-08-28 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_slaentry_service_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=65)),
                ('reason', models.TextField()),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.slaentry')),
            ],
        ),
    ]
