# Generated by Django 6.0.8 on 2026-08-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_slarating_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='slarating',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this rating belongs to a previous quarter.'),
        ),
    ]
