# Generated by Django 5.1 on 2024-08-28 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_slarating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slaentry',
            options={'verbose_name_plural': 'Sla entries'},
        ),
        migrations.AddField(
            model_name='slarating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slarating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
