# Generated by Django 5.1 on 2024-08-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_slaentry_options_slarating_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaImprovementPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvement_action', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Resolved'), (1, 'Met All'), (2, 'In Progress'), (3, 'Not Actioned')], default=3)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='core.slarating')),
            ],
        ),
    ]
