# Generated by Django 5.1 on 2024-08-28 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_slaimprovementplanentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaimprovementplanentry',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='core.slarating'),
        ),
    ]
