# Generated by Django 5.1 on 2024-08-29 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_slaimprovementplanentry_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaCustomerStatusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Resolved'), (1, 'Met All'), (2, 'In Progress'), (3, 'Not Actioned')], default=3)),
                ('improvement_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_status', to='core.slaimprovementplanentry')),
            ],
        ),
    ]
